on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: A job to extract links
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Links
        id: extralinks
        uses: mipmip/github-action-markdown-link-extract-to-json@v1.4
        with:
          section: Templates
          in-file: README.md
          out-file: templates_tmp.json

      - name: download embgit
        run: wget -c https://github.com/quiqr/embgit/releases/download/0.5.2/embgit_Linux_x86_64.tar.gz -O - | tar -xz

      - name: parse and flatten repo meta
        run: ./.github/workflows/getmeta.sh

          #      - name: Deploy
          #        uses: peaceiris/actions-gh-pages@v3
          #        with:
          #          github_token: ${{ secrets.GITHUB_TOKEN }}
          #          publish_dir: .
